### PR TITLE
(MODULES-2207) Modulesync

### PR DESCRIPTION
**Pull request by ferventcoder**
This brings the following items under modulesync:

* .gitignore
* .travis.yml
* CONTRIBUTING.md
* Gemfile
* appveyor.yml
* spec/spec.opts

Most importantly, this ensures that acl has up to date Gemfile, Travis CI and
AppVeyor configurations that allow it to be tested properly.

### CODE REVIEW

**Comment by Iristyle** [comment]
I believe this requires updating @ferventcoder

**Comment by ferventcoder** [comment]
Done.

**Comment by ferventcoder** [comment]
I have some files that snuck in here on file mode changes. I need to back those out

**Comment by ferventcoder** [comment]
There we go.

**Comment by Iristyle** [comment]
Validated combos of gems on each of the matrix cells in TravisCI and AppVeyor :+1:

**Pull request merged**
