### PR TITLE
(MODULES-1957) use original MOF gem

### PR DESCRIPTION
**Pull request by ferventcoder**
Blocked by #5.

Switch over to using original MOF parser from ruby gems.

Use WMI style instead of CIM.

### CODE REVIEW

**Comment by Iristyle** [comment]
I'm not sure I totally understand the `:wmi` vs `:cim` bit in f4fc491 - could you explain in a little more detail what the differences are?

https://github.com/kkaempf/mof/search?utf8=%E2%9C%93&q=style

**Comment by ferventcoder** [comment]
> I'm not sure I totally understand the :wmi vs :cim bit in f4fc491 - could you explain in a little more detail what the differences are?

Don't feel that you are alone in this trying to understand something that is not super well-documented.

But note that if you are using iconv, apparently the helper switches you over to wmi anyways. https://github.com/kkaempf/mof/blob/4bad8309c2cb453dd99ecbc5e6af99d2e3bd1cdf/lib/mof/helper.rb#L88

**Comment by Iristyle** [comment]
Yeah, interesting -- so it sniffs the file and turns on the `iconv` setting based on the byte order mark.

But I still think we should at least put *something* in the commit message about the `why` we needed to make the change / `what` it actually does.

I'm guessing it's related to what's mentioned in the projects [README](https://github.com/kkaempf/mof#featuresproblems) - https://msdn.microsoft.com/en-us/library/aa823192(VS.85).aspx

**Comment by ferventcoder** [comment]
> But I still think we should at least put something in the commit message about the *why* we needed to make the change / *what* it actually does.

I agree with this. It works, but not really sure what it does differently other than how it evaluates MOF files (and that is still a bit fuzzy to me on how it does that differently).

**Comment by ferventcoder** [comment]
Most of that is b/c there is very little documentation and the code appears to be abandonware. It's a risk factor to keep it around long term for sure. That's why I've been evaluating replacing it completely.

**Comment by Iristyle** [comment]
Can we just add a little bit more info to the commit msg @ferventcoder so that we can get this guy merged?

Maybe try to generate with `:cim` and `:wmi` and compare the output or something?

**Comment by ferventcoder** [comment]
> Maybe try to generate with :cim and :wmi and compare the output or something?

There is actually no difference in the output. I ran both of them and there were no visible changes in the underlying code. I think the real difference is in how it parses the MOF files.

**Comment by Iristyle** [comment]
Ok - playing devil's advocate a bit here - if the output isn't any different, then why did we need to change it?  I'm a little confused...

**Comment by ferventcoder** [comment]
We are making it more explicit.

**Pull request closed without merging**
