### PR TITLE
(MODULES-2559) Create Tests for "Package" DSC Resource

### PR DESCRIPTION
**Pull request by cowofevil**
Add acceptance tests for the DSC "Package" resource type. Updated the ERB
template to work with integers. [skip ci]

### CODE REVIEW

**Comment by phongdly** [comment]
Test failed on the different test that is not in this PR:
{code}
     Test Suite: tests @ 2015-09-14 13:46:22 -0700

      - Host Configuration Summary -


              - Test Case Summary for suite 'tests' -
       Total Suite Time: 1339.28 seconds
      Average Test Time: 20.93 seconds
              Attempted: 64
                 Passed: 63
                 Failed: 0
                Errored: 1
                Skipped: 0
                Pending: 0
                  Total: 64

      - Specific Test Case Status -
        
Failed Tests Cases:
Errored Tests Cases:
  Test Case tests/acceptance/tests/basic_dsc_resources/registry/reg_valid_dword_valuedata.rb reported: #<Beaker::Host::CommandFailure: Host 'pd55lyf4wggy59y.delivery.puppetlabs.net' exited with 1 running:
 cmd.exe /c puppet apply
Last 10 lines of output were:
	Notice: Compiled catalog for pd55lyf4wggy59y.delivery.puppetlabs.net in environment production in 0.45 seconds
	Error: Parameter dsc_valuedata failed on Dsc_registry[registry_test]: Invalid value '-2147483648'. Should be a string or an array of strings at line 1>
Skipped Tests Cases:
Pending Tests Cases:


Failed: errored in TestSuite: report_and_raise_on_failure
#<RuntimeError: Failed while running the tests suite>
No tests to run for suite 'post_suite'

You can reproduce this run with:
/Users/phongly/Box Sync/github/pr-review/ryan/puppetlabs-dsc/.bundle/gems/ruby/1.9.1/bin/beaker --preserve-hosts onfail --config tests/configs/windows-2012r2-64a --debug --tests tests/acceptance/tests --keyfile /Users/phongly//.ssh/id_rsa-acceptance --pre-suite tests/acceptance/pre-suite --load-path tests/lib --type aio

You can re-run commands against the already provisioned SUT(s) with:
/Users/phongly/Box Sync/github/pr-review/ryan/puppetlabs-dsc/.bundle/gems/ruby/1.9.1/bin/beaker --preserve-hosts onfail --config tests/configs/windows-2012r2-64a --debug --tests tests/acceptance/tests --keyfile /Users/phongly//.ssh/id_rsa-acceptance --pre-suite tests/acceptance/pre-suite --load-path tests/lib --type aio

Important ENV variables that may have affected your run:
    GEM_HOME		/Users/phongly/Box Sync/github/pr-review/ryan/puppetlabs-dsc/.bundle/gems/ruby/1.9.1
    GEM_PATH		
    PATH		/Users/phongly/Box Sync/github/pr-review/ryan/puppetlabs-dsc/.bundle/gems/ruby/1.9.1/bin:/opt/local/bin:/opt/local/sbin:/opt/crossfader/bin:/opt/crossfader/versions/ruby/1.9.3-p448/gemsets/crossfader/ruby/1.9.1/bin:/opt/crossfader/versions/ruby/1.9.3-p448/gemsets/global/ruby/1.9.1/bin:/opt/crossfader/versions/ruby/1.9.3-p448/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/Users/phongly/box/scripts
    home		/Users/phongly/
    puppet_agent_version		1.2.2
Failed running the test suite.

Phongs-MacBook-Pro:test_run_scripts phongly$
{code}

**Comment by cowofevil** [comment]
@phongdly Ready for review again.

**Comment by phongdly** [comment]
Looks like package_valid_msi.rb is included in package_uninstall.rb which has package with all valid "Name", "Path" and "ProductID" Specified'

**Comment by cowofevil** [comment]
@phongdly You are correct that "package_valid_msi.rb" is a subset of "package_uninstall.rb". Keeping them separate has the advantage that if a failure happens in one test, but not the other, that helps narrow down the root cause of failure for the developer.

**Pull request merged**
