### PR TITLE
(MODULES-3132) Update MOF Parser to modify files with a BOM

### PR DESCRIPTION
**Pull request by glennsarti**
The MOF parser used in the DSC module does not allow BOM (Byte Order Mark) in the text file.  This
can be introduced by third parties as this module depends on the upstream Powershell Github
repository.  This commit adds two steps to the rake rasks.  The first is a new rake task called
dsc:sanitize.  This will parse all MOF files and remove BOM markings if found.  The second is an
additional step to the build process which will scan all MOF files for BOM markings and fail early
if found.

Also in this commit the example SHA in the README_BUILD.md file is incremented to the latest
Powershell GitHub SHA.  This is required as the previous SHA did not include any files with a BOM.

### CODE REVIEW

**Comment by Iristyle** [comment]
Can probably squash this down @glennsarti and if you want to add a comment that says `paired-with: James Pogran <james.pogran@puppetlabs.com>` that's probably fine.

Also, minor nit that it looks like you're exceeding 72 chars in the commit msg body, so it's rendering a bit funny (on GitHub and in terminal)

**Comment by glennsarti** [comment]
Commits were squashed and commit message ammended

**Comment by Iristyle** [comment]
So in looking at this in more detail... wondering why you chose to go the rake route, rather than modifying the MOF parser code?

I opened up a PR showing the mods necessary to the MOF parser at https://github.com/puppetlabs/mof/pull/2.  Advantages:

* Less code changed (though admittedly it's a bit ugly)
* Parsing not performed in multiple locations
* Doesn't pull Charlock into our Rakefile (which we know won't work on Windows)
* Doesn't rewrite files (which could be considered undesirable)

In some rudimentary testing, the results appear to be the same (still could use some additional validation though).

**Comment by glennsarti** [comment]
I chose the Rake route to allow a user to independently verify the the MOF files prior to import i.e. fail fast.  Also by rewriting the file, a user would be able to verify the content of the file prior to import, if they wished e.g. What if the conversion process munged the file somehow?  If it's inline to the parsing then it's very difficult to diagnose that the content has changed.

That being said I can definitely see the advantages in using your suggested method.  I'll do a quick spike based on your PR and extended it to all possible BOMs and see if I can get the best of both ideas.

**Comment by Iristyle** [comment]
FWIW, I think all possible BOMs is probably overkill.  I would surprised to see anything other than UTF-16LE and UTF-8.  

Sublime can handle:

* `UTF-8 with BOM`
* `UTF-16LE with BOM`
* `UTF-16BE with BOM`

Notepad++ can handle:

* `UTF-8 with BOM`
* `UCS-2 LE with BOM`
* `UCS-2 BE with BOM`

Of course, `UCS-2` is a cousin to `UTF-16`, so I believe they are actually the same.  All of the other esoteric variations are ... well... esoteric.  I also wonder if any of their characters appear in legitimate content for the other encoding types (which could be problematic for us)

**Comment by Iristyle** [comment]
Also - I think your rake idea is useful, but maybe as a separate task outside of the normal workflow.  The MOF parser does currently tell you where it died (I have an incomplete branch that perhaps I should revive that will actually tell you all bad files rather than first bad file).  So I wouldn't be opposed to enabling the ability to file mangle up-front to rake tasks for the debugging reasons you describe.

However, I think there are a few things that make that less desireable in this PR:

* Encoding handling in multiple spots (I think that either rake OR lexer / parser would be best)
* If encoding handling is moved from the MOF parser, to external tasks, it is in turn less resilient as it now relies on the presence of the rake tasks to fix files for it (usually handling of encodings would be performed by a lexer / parser)
* I'll reiterate the Charlock Holmes / Windows compatibility point as well (would love to remove it from the process completely)

I think in an ideal world, the MOF parser library handles everything encoding related... and if we want to enable this rake task based workflow, there are would have some public helpers that the rake tasks could call.  Of course, that's a bit out of the scope of the current efforts here ;0

**Comment by Iristyle** [comment]
After pairing with @glennsarti, closing in favor of https://github.com/puppetlabs/mof/pull/2

**Pull request closed without merging**
