### PR TITLE
(DO NOT MERGE YET)(MODULES-4551) Update powershell_manager code

### PR DESCRIPTION
**Pull request by Iristyle**
- Move to the binary pipe code introduced as part of PowerShell
   module version 2.1.0:
   https://github.com/puppetlabs/puppetlabs-powershell/tree/2.1.0

 - This fixes any existing issues with UTF-8 content being passed
   between the Ruby parent and PowerShell child process

### CODE REVIEW

**Comment by Iristyle** [comment]
FYI @puppetlabs/windows @LarissaLane @ThoughtCrhyme - I threw this up really quick to get this on module team radar.... I'm sure it's going to require some additional work to properly integrate / get working.

This will need to be done for the UTF-8 launch - hopefully sooner.

**Comment by ThoughtCrhyme** [comment]
@eputnam triage all the things!

**Comment by Iristyle** [comment]
#288 should be merged first to fix the module metadata business

**Comment by Iristyle** [comment]
Similar to #261

**Comment by glennsarti** [comment]
@jpogran Is this PR superseded by https://github.com/puppetlabs/puppetlabs-dsc/pull/261 ?

**Comment by jpogran** [comment]
This is superseded by #261

**Pull request closed without merging**
