### PR TITLE
(MODULES-2615) Handle Empty Passwords for PSCredentials

### PR DESCRIPTION
**Pull request by jpogran**
Handle checking if a username or password is not provided better by
checking in the first iteration and not a second time.

### CODE REVIEW

**Comment by Iristyle** [comment]
:+1: as long as you ran acceptance and it passed?

**Comment by ferventcoder** [comment]
Also a thumbs up.

**Comment by ferventcoder** [comment]
Implement on types.

**Comment by jpogran** [comment]
@ferventcoder Types don't need to be updated because they look to see it raise an error, not for a string match. Should that be changed?

**Comment by ferventcoder** [comment]
@jpogran oh, missed that. Super awesome!

**Comment by Iristyle** [comment]
Ran through acceptance here at Puppet HQ - looks g2g.

**Comment by Iristyle** [comment]
And yeah, as a point of note - the more shared code that lives outside of the generated types, the better IMHO.

**Pull request merged**
