### PR TITLE
(WIP)(MODULES-2178) handle EmbeddedInstance classes

### PR DESCRIPTION
**Pull request by Iristyle**

### CODE REVIEW

**Comment by Iristyle** [comment]
Supercedes #88

**Comment by Iristyle** [comment]
@jpogran you can take a look at the first 3 commits... commit 4 still needs some cleanup and the 5th commit I had working at one point, but reshuffled a bit with some refactoring and need to get back into a better state.


Since I didn't re-gen types / tests in that last commit, you should be able to grab this PR locally and test against pertinent DSC resources @jpogran / @ferventcoder

**Comment by Iristyle** [comment]
Also @cowofevil you can use this branch to work against credentials now, even though the PR isn't entirely complete yet.

**Comment by Iristyle** [comment]
Ok @jpogran / @ferventcoder this still needs a bit more polish (as of 310aef0) but it's pretty close to the final implementation on this one (after many many iterations).

Obviously we still have issues with making the 2 embedded instance types work properly when calling `Invoke-DscResource` - but that might need to be resolved in a future commit base on the response we get there.

So review away!

**Comment by Iristyle** [comment]
@jpogran `New-CimInstance` is in place and ready for additional testing.  It passed some quick sanity tests locally, but I haven't exhaustively put it through the ringer.

I'm about to kick off an acceptance run before I hit the hay....

**Comment by Iristyle** [comment]
Phew... one more round of updates to the commits.

Please try and break some more @jpogran / @ferventcoder.  Each commit passes specs, but I may backfill a few more tests around the trickiest bits.

**Comment by Iristyle** [comment]
Looks like all the commit messages need to be updated with `MODULES-2178`

**Comment by Iristyle** [comment]
Requires #102 to be merged first

**Comment by Iristyle** [comment]
@jpogran / @ferventcoder this has been cleaned up to no longer use the provider for helper methods.  Some of the code generation has changed slightly as a result to make sure the code still works properly.

Please have a look / test out.

**Comment by Iristyle** [comment]
Also FYI - once #102 is merged, I can rebase this on master and repush if necessary.

**Comment by ferventcoder** [comment]
#102 was merged :)

**Comment by Iristyle** [comment]
Yup, you sent that up after I had already rebased ;0

**Comment by jpogran** [comment]
LGTM. Tested on win2012R2 with wmf 5 production preview.

**Comment by ferventcoder** [comment]
LGTM as well.

**Pull request merged**
