### PR TITLE
(MODULES-5548) Remove powershell and stdlib modules

### PR DESCRIPTION
**Pull request by jpogran**
This commit removes the dependency on the powershell and stdlib modules
from the dsc module. This was annouced and warned in the 1.4 release in
commit d5f8072d71fdab6c285b68fc58a4d01b52eea4ca.

### CODE REVIEW

**Comment by glennsarti** [comment]
Missed:
https://github.com/puppetlabs/puppetlabs-dsc/blob/master/.fixtures.yml#L3-L4
https://github.com/puppetlabs/puppetlabs-dsc/blob/master/tests/acceptance/pre-suite/02_dsc_module_install.rb#L23-L24

**Comment by jpogran** [comment]
@glennsarti updated

**Comment by glennsarti** [comment]
Kicked off adhoc build to be sure.

**Comment by glennsarti** [comment]
Passed adhoc.  Ready to mergey merge

**Comment by glennsarti** [comment]
nit: powershell mis-spelt

**Comment by jpogran** [comment]
Typo fixed, travis no longer broken, however appveyor most likely wont pass due to ffi

**Comment by Iristyle** [comment]
Rekicked now that 1.9.21 FFI gems are up for Windows - passed AppVeyor

**Comment by Iristyle** [comment]
Forgot I had broken that commit out at https://github.com/puppetlabs/puppetlabs-dsc_lite/commit/712c455633e801232716e0c9c7de07242fa7dd29 so it could be cherry-picked over here...

**Comment by jpogran** [comment]
Updated. The README line is explaining that you need administrative permissions to set the LCM RefreshMode, but doesn't actually refer to this module setting it, but I removed it anyway to avoid potential confusion

**Pull request merged**
