### PR TITLE
(maint) Re-vendor DSC resources at 8ff0237

### PR DESCRIPTION
**Pull request by Iristyle**
Builds on #206 

- [x] Commit msg needs to be updated

### CODE REVIEW

**Comment by Iristyle** [comment]
We might also want to hold off on merging this until the submodule changes are merged at:

https://github.com/PowerShell/xActiveDirectory/pull/98
https://github.com/PowerShell/xDhcpServer/pull/25

 We'll then want to put up a PR to the parent DSCResources repo with the bumped submodule versions.

**Comment by jpogran** [comment]
Both PRs have been merged, this is clear to go 👍

**Comment by Iristyle** [comment]
Well, we still have a few conditions before merging this:

- [ ] - #206 should be merged
- [ ] - PR https://github.com/PowerShell/DscResources/pull/139 for `xActiveDirectory` should be merged
- [ ] - PR https://github.com/PowerShell/DscResources/pull/140 for `xDhcpServer` should be merged

**Comment by ferventcoder** [comment]
Does #218 supersede this since it will have updates of the modules after merge?

**Comment by ferventcoder** [comment]
Considering this superseded by the PR that @glennsarti is about to put up.

**Comment by ferventcoder** [comment]
Superseded by #221

**Pull request closed without merging**
