### PR TITLE
(MODULES-2692) Update to latest upstream DSC

### PR DESCRIPTION
**Pull request by Iristyle**
Will rebase and repush once #114 is merged.

Also waiting on https://github.com/PowerShell/DscResources/pull/61 to be merged so we can move past https://github.com/PowerShell/DscResources/commits/27aa83e

### CODE REVIEW

**Comment by Iristyle** [comment]
FYI @jpogran the last 2 commits here update the types and providers accordingly.

**Comment by ferventcoder** [comment]
Goodies... love that commit message

**Comment by Iristyle** [comment]
All set for review @jpogran / @ferventcoder

**Comment by ferventcoder** [comment]
ib/puppet_x/dsc_resources/xSharePoint/.gitattributes and .gitignore - those need to be removed. Other than that, LGTM.

**Comment by Iristyle** [comment]
Looks like there might be a rake task issue at https://github.com/puppetlabs/puppetlabs-dsc/blob/master/build/dsc.rake#L74

**Pull request merged**
