### PR TITLE
(WIP)(MODULES-2760) Refactor Type Validation / Remove Unneeded Tests

### PR DESCRIPTION
**Pull request by Iristyle**

### CODE REVIEW

**Comment by Iristyle** [comment]
@puppetlabs/windows this is just the starting point on this one - more work to be done.  But this shows how we can remove a number of spec tests based on modifying how / munging validation can be called through a shared helper / tested outside of the class.

**Comment by lionce** [comment]
Hello @Iristyle ,

If you still want to merge this PR, please resolve conflicts and rebase it with the latest changes. 

Thanks!

**Comment by david22swan** [comment]
@Iristyle 
Sorry to bother you but I was just wondering whether or not you intended to return to this PR at any point?
What I can see look's good.

**Comment by david22swan** [comment]
@Iristyle 
Closing this PR as the work enclosed has been largely replaced by puppetlabs-dsc_lite.

**Pull request closed without merging**
