### PR TITLE
(MODULES-4422) PS Module Manifest Parser bug

### PR DESCRIPTION
**Pull request by jpogran**
This fixes the regex that parses the PS module mainfest file (psd1) so that it can handle both single and double quoted strings

### CODE REVIEW

**Comment by glennsarti** [comment]
Do we need some tests around this?

**Comment by nealpeters86** [comment]
Tested with 3 custom modules;
The fix is working for the cChoco module, also building 2 other custom modules is still working as expected! Thanks @jpogran!

**Comment by jpogran** [comment]
@nealpeters86 thanks for the verification. I am still going to put some kind of spec test for this like @glennsarti says, as it's obviously a blind spot

**Comment by glennsarti** [comment]
@jpogran CI is green

**Comment by glennsarti** [comment]
Given a customer has verified the fix, and my commit was to fix up CI tests due to Gem loading, while normally I would not merge my own commits, in this case this seems ok.

**Pull request merged**
