### PR TITLE
(MAINT) refactor dsc tests to include --detailed-exitcodes

### PR DESCRIPTION
**Pull request by ThoughtCrhyme**
Refactor unicode tests into their own .rb file

Removed unneeded helper methods.

Changed variable scope to be more sane.

### CODE REVIEW

**Comment by glennsarti** [comment]
Hrmm looks like Gem has been upgraded from 2.7.6 to 2.7.7 and it no longer considers `5.0.10586.117` a valid version

``` powershell
select [1]-[2] to use that specific ruby (0 to exit) [0]: 1
---> now using ruby 2.4.3-p205 tagged as `2.4.3-2-x64`
C:\Source> ruby -e "Gem::Version.new('5.0.10586.117')"
-e:1: unexpected fraction part after numeric literal
Gem::Version.new(5.0.10586.117)
                    ^
-e:1: syntax error, unexpected tINTEGER, expecting ')'
Gem::Version.new(5.0.10586.117)
```

**Comment by glennsarti** [comment]
Yup - https://github.com/rubygems/rubygems/commit/2ec7eb07932951e551ca80fc15f26f3a26af14ef

`(Gem::Version.new(Facter.value(:powershell_version))`

I assume that `Facter.value(:powershell_version)` is evaluating as nil thus we tripped the new behaviour.

**Comment by RandomNoun7** [comment]
Ethan merged #373 for us, so if you rebase, these might start to work.

**Comment by ThoughtCrhyme** [comment]
These changes are no longer pertinent due to the changes merged in https://github.com/puppetlabs/puppetlabs-dsc/pull/380

Closing this.

**Pull request closed without merging**
