### PR TITLE
(MODULES-2777) Build all DSC Types

### PR DESCRIPTION
**Pull request by jpogran**
Update all types to the latest import from the DSC Resources repo to sha 84a467c

### CODE REVIEW

**Comment by Iristyle** [comment]
Can we note in here what SHA we used as the basis for this?

**Comment by Iristyle** [comment]
@jpogran mind doing a quick change to commit msg like:

```
(MODULES-2777) Rebuild all DSC Types at 84a467c

    Update all types to the latest import from the DSC Resources repo:
    https://github.com/PowerShell/DscResources/commit/84a467c303
```

**Comment by jpogran** [comment]
TIL github makes clickable links in commit messages. Nice

**Comment by Iristyle** [comment]
@jpogran yup...for bare SHAs it will create one in current repo.  For full urls, it makes them clickable (and fancies them up for other GitHub repos)

**Pull request merged**
