### PR TITLE
[WIP - DO NOT MERGE](FM-2563)

### PR DESCRIPTION
**Pull request by ferventcoder**

### CODE REVIEW

**Comment by Iristyle** [comment]
@ferventcoder if you push up your latest on this one, I can do some more work on it later today after I wrap up the changes around `MSFT_KeyValuePair`, `MSFT_Credentials` and friends

**Comment by ferventcoder** [comment]
@Iristyle Sure thing, will have this up by the end of my day.

**Comment by glennsarti** [comment]
@ferventcoder Can I close this PR?

**Comment by ferventcoder** [comment]
We can close this for now, sure

**Pull request closed without merging**
